config/routes.rb
Rails.application.routes.draw do
  
  get 'users/new'

  resources :song_aliases
  resources :songs
  resources :shows
  resources :venues
  root 'application#hello'
  

end

app/controllers/song_aliases_controller.rb
class SongAliasesController < ApplicationController
  before_action :set_song_alias, only: [:show, :edit, :update, :destroy]

  # GET /song_aliases
  # GET /song_aliases.json
  def index
    @song_aliases = SongAlias.all
  end

  # GET /song_aliases/1
  # GET /song_aliases/1.json
  def show
  end

  # GET /song_aliases/new
  def new
    @song_alias = SongAlias.new
  end

  # GET /song_aliases/1/edit
  def edit
  end

  # POST /song_aliases
  # POST /song_aliases.json
  def create
    @song_alias = SongAlias.new(song_alias_params)

    respond_to do |format|
      if @song_alias.save
        format.html { redirect_to @song_alias, notice: 'Song alias was successfully created.' }
        format.json { render :show, status: :created, location: @song_alias }
      else
        format.html { render :new }
        format.json { render json: @song_alias.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /song_aliases/1
  # PATCH/PUT /song_aliases/1.json
  def update
    respond_to do |format|
      if @song_alias.update(song_alias_params)
        format.html { redirect_to @song_alias, notice: 'Song alias was successfully updated.' }
        format.json { render :show, status: :ok, location: @song_alias }
      else
        format.html { render :edit }
        format.json { render json: @song_alias.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /song_aliases/1
  # DELETE /song_aliases/1.json
  def destroy
    @song_alias.destroy
    respond_to do |format|
      format.html { redirect_to song_aliases_url, notice: 'Song alias was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song_alias
      @song_alias = SongAlias.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_alias_params
      params.require(:song_alias).permit(:song_id, :alias)
    end
end

app/helpers/song_aliases_helper.rb
module SongAliasesHelper
end

app/views/song_aliases/_form.html.erb
<%= form_for(song_alias) do |f| %>
  <% if song_alias.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song_alias.errors.count, "error") %> prohibited this song_alias from being saved:</h2>

      <ul>
      <% song_alias.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :song_id %>
    <%= f.number_field :song_id %>
  </div>

  <div class="field">
    <%= f.label :alias %>
    <%= f.text_field :alias %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/song_aliases/edit.html.erb
<h1>Editing Song Alias</h1>

<%= render 'form', song_alias: @song_alias %>

<%= link_to 'Show', @song_alias %> |
<%= link_to 'Back', song_aliases_path %>

app/views/song_aliases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Song Aliases</h1>

<table>
  <thead>
    <tr>
      <th>Song</th>
      <th>Alias</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @song_aliases.each do |song_alias| %>
      <tr>
        <td><%= song_alias.song_id %></td>
        <td><%= song_alias.alias %></td>
        <td><%= link_to 'Show', song_alias %></td>
        <td><%= link_to 'Edit', edit_song_alias_path(song_alias) %></td>
        <td><%= link_to 'Destroy', song_alias, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song Alias', new_song_alias_path %>

app/views/song_aliases/new.html.erb
<h1>New Song Alias</h1>

<%= render 'form', song_alias: @song_alias %>

<%= link_to 'Back', song_aliases_path %>

app/views/song_aliases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Song:</strong>
  <%= @song_alias.song_id %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @song_alias.alias %>
</p>

<%= link_to 'Edit', edit_song_alias_path(@song_alias) %> |
<%= link_to 'Back', song_aliases_path %>